### ISSUE TITLE
Debugging 403 errors from Cybersource gateway

### ISSUE THREAD

**Issue by mshamma** [wharton/django-cybersource-hosted-checkout#1]
Hi Timothy (I presume),

Intros:  I'm a Web developer at UC Berkeley and we're in the midst of migrating one of our legacy sites to Django.  It's a ColdFusion site that we've integrated with Cybersource back in the stone age.  ;-)  

First I'd like to thank you for sharing your code on Github.  I've incorporated the signing portion of the code (e.g. utils.py) into our Django solution.  However, I'm receiving a 403 error from the Cybersource gateway.  

I know this isn't an issue with your code, but I was hoping you might have any tips or insight for us.  This is our first Django integration with Cybersource Hosted Order Page.  

Best,

Mohammed Shamma
Senior Web Application Developer
External Relations & Marketing Communications
University Development & Alumni Relations

Give to Berkeley | give.berkeley.edu
Twitter | twitter.com/cal
Cal alumni network | cal.berkeley.edu

**Comment by FlipperPA** [comment]
@mshamma Apologies, I didn't get a notice that you'd opened an issue!  Since this is through Wharton, it is best to tag me @FlipperPA on any issues opened. I hope you got it figured out, but most times people get tripped up is because the time isn't set properly in the development environment.

Let me know if you're still having issues and we can dig deeper.

**Comment by RobertoPotato** [comment]
Hi. I am also facing the same issue. I have used various timezones including UTC+3 (my current TimeZone) and the UTC without any offset. I have also made sure to sign all the necessary fields as well as added them to the signed field names parameter.

**Comment by FlipperPA** [comment]
@RobertoPotato I don't think you should be including the `signed_date_time` field; I included it automatically here:

https://github.com/wharton/django-cybersource-hosted-checkout/blob/master/cybersource_hosted_checkout/utils.py#L27

The `sign_fields_to_context` function should automatically take everything you've added to `fields`, and wrap it up together with the signature.

**Comment by RobertoPotato** [comment]
Hello @FlipperPA. You were very right! I was including the signed_date_time by myself instead of letting your function handle it. I changed it and now have transactions that are going through. THANK YOU!!

**Comment by FlipperPA** [comment]
@RobertoPotato Fantastic! I'm glad we got it figured out. And thanks for the reminder to close out this old issue. Best of luck!
